{% set name = "fakeredis" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7c657d6345f3a9837be1ed118964ba2472f66083d325017edad917b560c01a78

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python
    - redis-py
    - six >=1.12
    - sortedcontainers
  run:
    - python
    - redis-py
    - six >=1.12
    - sortedcontainers

test:
  imports:
    - fakeredis

about:
  home: https://github.com/jamesls/fakeredis
  license: BSD
  license_family: BSD
  license_file: COPYING
  summary: Fake implementation of redis API for testing purposes.

extra:
  recipe-maintainers:
    - Bezier89
    - pg-hbk
