{% set name = "fakeredis" %}
{% set version = "1.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 790c85ad0f3b2967aba1f51767021bc59760fcb612159584be018ea7384f7fd2

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python
    - redis-py
    - six >=1.12
    - sortedcontainers
  run:
    - python
    - redis-py
    - six >=1.12
    - sortedcontainers

test:
  imports:
    - fakeredis

about:
  home: https://github.com/jamesls/fakeredis
  license: BSD
  license_family: BSD
  license_file: COPYING
  summary: Fake implementation of redis API for testing purposes.

extra:
  recipe-maintainers:
    - Bezier89
    - pg-hbk
