{% set name = "fakeredis" %}
{% set version = "2.10.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 17415645d11994061f5394f3f1c76ba4531f3f8b63f9c55a8fd2120bebcbfae9

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.7
    - redis-py
    - sortedcontainers
    - poetry
  run:
    - python >=3.7,<4
    - redis-py <4.4
    - six >=1.12
    - sortedcontainers >=2.4.0,<3

test:
  imports:
    - fakeredis

about:
  home: https://github.com/cunla/fakeredis-py
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Implementation of Redis in python. fully compatible with using redis-py.

extra:
  recipe-maintainers:
    - cunla
