{% set name = "fakeredis" %}
{% set version = "2.26.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6396bfbbf8aea94edba61365f52521491a5565349a7cdc420f8f3ad8f5183ba5

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.7
    - redis-py
    - sortedcontainers
    - poetry
  run:
    - python >=3.7,<4
    - redis-py >=4
    - sortedcontainers >=2.4.0,<3

test:
  imports:
    - fakeredis

about:
  home: https://github.com/cunla/fakeredis-py
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Fake implementation of redis API (redis-py) for testing purposes.

extra:
  recipe-maintainers:
    - cunla
