{% set name = "fakeredis" %}
{% set version = "1.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b0b64d0fe0e491752006c1880eacac647ed30a12a13066e0cea54449778ad811

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
    - redis-py
    - six >=1.12
    - sortedcontainers
  run:
    - python
    - redis-py
    - six >=1.12
    - sortedcontainers

test:
  imports:
    - fakeredis

about:
  home: https://github.com/jamesls/fakeredis
  license: BSD
  license_family: BSD
  license_file: COPYING
  summary: Fake implementation of redis API for testing purposes.

extra:
  recipe-maintainers:
    - Bezier89
    - pg-hbk
