{% set name = "fakeredis" %}
{% set version = "2.27.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7b7584ec104392592297f46864a82cb7339a23e254ee885bf5ae07cfc64fbce7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry-core
  run:
    - python >={{ python_min }},<4
    - redis-py >=4.3
    - sortedcontainers >=2.4.0,<3
    - typing-extensions >=4.7,<5

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - fakeredis
  commands:
    - pip check

about:
  home: https://github.com/cunla/fakeredis-py
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Fake implementation of redis API (redis-py) for testing purposes.

extra:
  recipe-maintainers:
    - cunla
    - synapticarbors
