schema_version: 1

context:
  name: fakeredis
  version: "2.31.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 76dfb92855f0787a4936a5b4fdb1905c5909ec790e62dff2b8896b412905deb0

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - hatchling
  run:
    - python >=${{ python_min }},<4
    - redis-py >=4.3
    - sortedcontainers >=2.4.0,<3
    - typing-extensions >=4.7,<5

tests:
  - python:
      imports:
        - fakeredis
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Fake implementation of redis API (redis-py) for testing purposes.
  homepage: https://github.com/cunla/fakeredis-py

extra:
  recipe-maintainers:
    - cunla
    - synapticarbors
